version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node:1642eaf
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
      - postgres
      - ganache
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'ganache:http://ganache:8545'
      GRAPH_LOG: info
      GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE: 10
      ETHEREUM_REORG_THRESHOLD: 10
      ETHEREUM_POLLING_INTERVAL: 250

  ipfs:
    image: ipfs/kubo:v0.17.0
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs:Z

  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements",
        "-cmax_connections=200"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:Z

  ganache:
    image: trufflesuite/ganache-cli:v6.12.2
    ports:
      - '8545:8545'
    command:
      - -b 2
      - --host=0.0.0.0
      - --networkId=1337
      - --accounts=10
      - --defaultBalanceEther=10000
      - --db=/ganache/data
      - --mnemonic=test test test test test test test test test test test junk
    volumes:
      - ./data/ganache:/ganache:Z
